### PR TITLE
Fix bravado_core regression when internally_dereference_refs is in use

### LINKED ISSUE #275: Identified regression in bravado_core.spec.Spec if internally_dereference_refs is enabled
A regression as been introduced by https://github.com/Yelp/bravado-core/commit/d23868c9cc87f30a208765b73b88dd0c12c08cad.

Affected versions
------------------
bravado-core: 4.13.3, 4.13.4, 5.0.0 and 5.0.1

Symptoms
----------
After initialising a `bravado.client.SwaggerClient` with `internally_dereference_refs` config enabled you're not able to communicate with the service.
The traceback will look like
```
  File "/home/maci/pg/test_service/virtualenv_run/lib/python3.6/site-packages/bravado/client.py", line 243, in __call__
    self.operation, request_options, **op_kwargs)
  File "/home/maci/pg/test_service/virtualenv_run/lib/python3.6/site-packages/bravado/client.py", line 271, in construct_request
    url = operation.swagger_spec.api_url.rstrip('/') + operation.path_name
AttributeError: 'NoneType' object has no attribute 'rstrip'
```
Motivations
-----------
While working on #263 I've ensured that resources are rebuilt in case `internally_dereference_refs` is set.
This was made in order to guarantee that all the references (on the already built resources) were stripped out, so after building the `Spec` object no references will be available.
Unfortunately, `build_resource` will save a pointer to the used `Spec` instance into the resource itself but we're using a temporary instance that was not fully initialised.
The effect of this is that a `Spec` instance that is fully dereferenced will, internally, point to an other `Spec` instance bind into `Operation` instances (the pointed `Spec` instance will be used to send requests, validate responses, etc).

How to fix this
--------------
The results of the regression is that `Spec` object could raise weird exceptions due to undefined `api_url` and uses double the memory needed (which is sad too).

To fix the issue will be sufficient to replace `build_resources(tmp_spec)` with `build_resources(swagger_spec)` but we need to ensure that at that time `_internal_spec_dict` has been updated to point toward the dereferenced version of the spec dict.

How to reproduce and test
--------------------------
```python
spec_dict = {
    "swagger": "2.0",
    "info": {"title": "Test", "version": "1.0"},
    "paths": {
        "/endpoint": {
            "get": {
                "operationId": "operation",
                "responses": {"200": {"description": "random response"}},
                "tags": ["tag"],
            }
        }
    },
}
spec = Spec.from_dict(spec_dict, config={'internally_dereference_refs': True})
spec_in_object = spec.resources['tag'].operations['operation'].swagger_spec
assert spec == spec_in_object
```

### PR DESCRIPTION
**Pull request by macisamuele**
Fixes #275 

PR #263 introduced a regression in the library when `internally_dereference_refs` is enabled.
The regression symptoms and causes are more deeply described on issue #275, I'll mention here few points that will allow me to explain how the changes in this PR will solve the regression.

https://github.com/Yelp/bravado-core/commit/d23868c9cc87f30a208765b73b88dd0c12c08cad split resource discovery in order to be executed before getting `Spec.deref_flattened_spec` and after to guarantee that resources points to a spec dict without references, unfortunately approach created two _independent_ instances of `Spec` (check `test_swagger_spec_in_operation_is_the_swagger_spec_that_contains_the_operation` on the affected version of the library).

Having resources built before flattening was a _requirement_ of `Spec.flattened_spec`; the requirement was added to guarantee that models present on the original specs will continue to be available after the flattening process.
This PR removes the strict requirement of having resources built before flattening, as in order to guarantee that all the models are present after flattening we should keep into account the content of `Spec.definitions` and not `Spec.resource`.

An other change provided by this PR is to remove `Spec. _validate_config` which checked that `internally_dereference_refs` could be used only if `validate_swagger_spec` was enabled.
This config dependency had the unique scope of ensuring that generated flattened specs are valid swagger specs (as we can only guarantee that starting from valid specs we can generate valid specs).
This adds complexity (and a not negligible time-penalty) that could be avoided if the user of the library assumes that read specs are valid specs.

### CODE REVIEW

File: bravado_core/spec.py [hunk 1]
```diff
@@ -301,16 +283,14 @@ def security_definitions(self):
...
 
         if not self.config['validate_swagger_spec']:
-            raise RuntimeError('Swagger Specs have to be validated before flattening.')
-
-        # If resources are defined it means that Spec has been built and so swagger specs have been validated
-        if self.resources is None:
-            self.build()
+            log.warning(
+                'Flattening unvalidated specs could produce invalid specs. '
+                'Use it at your risk or enable `validate_swagger_specs`',
```
[the remark this answers is not in the document]
Comment (sjaensch) [reply bravado_core/spec.py]: I'm not sure about the impact that flattening could have; are you saying specs could be much worse after flattening? Then we should keep the warning.

[the remark this answers is not in the document]
Comment (macisamuele) [reply bravado_core/spec.py]: I'm not able to estimate how worst respect the original (potentially invalid specs) the output could be.
So I would prefer to be conservative and have the warning.
